#!/usr/local/bin/python3
import sys
import os

if len(sys.argv) != 2:
    print("Usage: ")
    print("    fgit https://github.com/EdgeSecurityTeam/EHole")
    print("    fgit https://github.com/EdgeSecurityTeam/EHole/archive/main.zip")
    print("    fgit https://github.com/EdgeSecurityTeam/EHole/releases/download/v2.0/Ehole2.0-darwin.zip")
    print("    fgit https://raw.githubusercontent.com/EdgeSecurityTeam/EHole/main/README.md")
    exit(1)

url = sys.argv[1]
if 'releases' in url or 'archive' in url:
    os.system('wget {}'.format(url.replace('github.com', 'download.fastgit.org')))
elif 'raw.githubusercontent.com' in url:
    os.system('wget {}'.format(url.replace('raw.githubusercontent.com', 'raw.fastgit.org')))
else:
    os.system('git clone {}'.format(url.replace('github.com', 'hub.fastgit.org')))
